### ISSUE TITLE
"commentValueIndent" should be 1 instead of 0 by default

### ISSUE THREAD

**Issue by BoomEaro** [Elytrium/java-serializer#4]
https://github.com/Elytrium/java-serializer/blob/61d9ece31a32cd3748dd13787315dd7a4cca5ff8/src/main/java/net/elytrium/serializer/annotations/Comment.java#L47-L55
The documentation shows an example of what a comment looks like when using the comment format.
However, this example only contains indentation, which is disabled by default, which is confusing. 
Besides this default behavior is different from the old configuration framework, where the default was always only 1 indentation.

**Comment by hevav** [comment]
It should not be 1, since we want to implement binary serializers (e.g. NBT, MessagePack) in near future. Binary-serialized comments should not be prepended with spaces.
